housing_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('whistleblower.urls')),
]

whistleblower/urls.py
from django.urls import include, path
from . import views

app_name = "whistleblower"
urlpatterns = [
    path('', views.home, name='home'),
    path('level-select/', views.level_select, name='level_select'),
    path('level-admin/', views.level_admin, name='level_admin'),
    path('level-user/', views.level_user, name='level_user'),
    path('home-anon/', views.anon_home, name='home_anon'),
    path('home-admin/', views.home_admin, name='home_admin'),
    path('login/', views.login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('neighbor-form/', views.neighbor_complaint, name='n-complaint'),
    path('building-form/', views.building_complaint, name='b-complaint'),
    path('success/', views.success, name='success'),
    path('failure/', views.failure, name='failure'),
    path('view-report/<int:pk>/', views.ReportView.as_view(), name='report_view'),
    path('create-group/', views.create_building_group_page, name='create_group_page'),
    path('create-group/confirm', views.create_building_group, name='create_group'),
    path('join-group/', views.join_building_group_page, name='join_group_page'),
    path('join-group/confirm/', views.join_building_group, name="join_group"),
    path('mark_as_resolved/<int:report_id>/', views.mark_as_resolved, name='mark_as_resolved'),
    path('reopen_report/<int:report_id>/', views.reopen_report, name='reopen_report'),
    path('no-access/', views.no_access, name='no_access'),
    path('leave-group/<int:code>/', views.leave_building_group, name='leave_building_group'),
    path('neighbor-anonymous-form/', views.neighbor_anon_complaint, name='n-a-complaint'),
    path('building-anonymous-form/', views.building_anon_complaint, name='b-a-complaint'),
    path('delete/<int:report_id>/', views.delete_complaint, name='delete'),
]

whistleblower/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


# Create your models here.
class BuildingGroup(models.Model):
    name = models.CharField(max_length=50, null=False)
    User = get_user_model()
    users = models.ManyToManyField(User, null=True)


class Complaint(models.Model):
    class ComplaintType(models.IntegerChoices):
        NOISE_COMPLAINT = 1, "Noise Complaint"
        MESSINESS = 2, "Messiness"
        STOLEN_ITEM = 3, "Stolen Item"
        MAINTENANCE = 4, "Maintenance"
        PROPERTY_DAMAGE = 5, "Property Damage"
        PARKING_LOT = 6, "Parking Lot"
        LOITERING = 7, "Loitering"
        OTHER = 8, "Other"

    class ComplaintStatus(models.IntegerChoices):
        NEW = 1, "New"
        IN_PROGRESS = 2, "In Progress"
        RESOLVED = 3, "Resolved"

    # All Personal Information is Optional
    reporter = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    resolution_notes = models.TextField(max_length=500, null=True, blank=True)
    reporter_first_name = models.CharField(max_length=50, null=True, blank=True)
    reporter_last_name = models.CharField(max_length=50, null=True, blank=True)
    reporter_email = models.CharField(max_length=50, null=True, blank=True)
    # All Personal Information is Optional

    complaint_title = models.CharField(verbose_name="Title*", max_length=200)
    type_complaint = models.PositiveSmallIntegerField(
        choices=ComplaintType.choices, default=ComplaintType.NOISE_COMPLAINT, verbose_name="Complaint Type*")
    sent_date = models.DateTimeField("Date Sent", auto_now_add=True)
    incident_date = models.DateTimeField("Date of Incident*")
    respondent_name = models.CharField(max_length=50, null=True, blank= True, verbose_name="Respondent Name")
    location_address = models.CharField(max_length=50, verbose_name="Location Address*")
    location_description = models.TextField(max_length=500, verbose_name="Location Description*")
    incident_description = models.TextField(max_length=500, null=True, blank=True, verbose_name="Incident Description")
    # Need to work out how to upload and connect file upload
    file1 = models.FileField(upload_to="report_files", null=True, blank=True, verbose_name="File 1")
    file2 = models.FileField(upload_to="report_files", null=True, blank=True, verbose_name="File 2")
    file3 = models.FileField(upload_to="report_files", null=True, blank=True, verbose_name="File 3")
    additional_information = models.TextField(max_length=500, null=True, blank=True, verbose_name="Additional Information")
    urgency = models.IntegerField(verbose_name="How urgent from 1 to 5?*", default=1)
    complaint_status = models.PositiveSmallIntegerField(
        choices=ComplaintStatus.choices, default=ComplaintStatus.NEW)
    group = models.ForeignKey(BuildingGroup, on_delete=models.CASCADE, null=True, verbose_name="Building Group*")

    def complaint_status_phrase(self):
        status_mapping = {
            self.ComplaintStatus.NEW: "New",
            self.ComplaintStatus.IN_PROGRESS: "In Progress",
            self.ComplaintStatus.RESOLVED: "Resolved"
        }
        return status_mapping.get(self.complaint_status, "Unknown")

    def complaint_type_phrase(self):
        complaint_mapping = {
            self.ComplaintType.NOISE_COMPLAINT: "Noise Complaint",
            self.ComplaintType.MESSINESS:  "Messiness",
            self.ComplaintType.STOLEN_ITEM: "Stolen Item",
            self.ComplaintType.MAINTENANCE:  "Maintenance",
            self.ComplaintType.PROPERTY_DAMAGE: "Property Damage",
            self.ComplaintType.PARKING_LOT: "Parking Lot",
            self.ComplaintType.LOITERING: "Loitering",
            self.ComplaintType.OTHER: "Other"
        }
        return complaint_mapping.get(self.type_complaint, "Other")

    def delete(self, *args, **kwargs):
        self.file1.delete(save=False)
        self.file2.delete(save=False)
        self.file3.delete(save=False)
        super().delete(*args, **kwargs)

whistleblower/views.py
from time import timezone

from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import logout
from django.contrib.auth.models import Group
from django.contrib import messages
from django.views import generic
from .forms import NComplaintForm
from .forms import BComplaintForm, ABComplaintForm, ANComplaintForm
from .models import Complaint, BuildingGroup
from django.contrib.auth.models import User, AnonymousUser

import os
import boto3
from botocore.exceptions import NoCredentialsError


# Tutorial used to figure out login:
# https://anmol-garg.medium.com/adding-google-oauth-2-0-to-your-django-project-the-easy-way-9df3d87d16fd

def home(request):
    if Group.objects.count() < 3:
        create_groups()
    user = request.user
    if user.is_authenticated:
        if not user.groups.filter(name="User") and not user.groups.filter(name="Admin") and not user.groups.filter(
                name="SuperAdmin"):
            return HttpResponseRedirect(reverse("whistleblower:level_select"))
        context = {
            'name': user.username.capitalize(),
            'open_reports': Complaint.objects.filter(reporter=user,
                                                     complaint_status__in=[Complaint.ComplaintStatus.NEW,
                                                                           Complaint.ComplaintStatus.IN_PROGRESS]),
            'closed_reports': Complaint.objects.filter(reporter=user,
                                                       complaint_status=Complaint.ComplaintStatus.RESOLVED),
            'is_admin': user.groups.filter(name="Admin"),
            'is_superadmin': user.groups.filter(name="SuperAdmin"),
            'groups': BuildingGroup.objects.filter(users=request.user)
        }
        if user.groups.filter(name="Admin") or user.groups.filter(name="SuperAdmin"):
            return HttpResponseRedirect('/home-admin')
        else:
            return render(request, "whistleblower/home.html", context)

    return HttpResponseRedirect('/login')


def create_groups():
    if not Group.objects.filter(name="User"):
        Group.objects.create(name="User")
    if not Group.objects.filter(name="Admin"):
        Group.objects.create(name="Admin")
    if not Group.objects.filter(name="SuperAdmin"):
        Group.objects.create(name="SuperAdmin")
    return


def level_select(request):
    return render(request, "whistleblower/level_select.html")


def level_admin(request):
    request.user.groups.add(Group.objects.get(name="Admin"))
    return HttpResponseRedirect('/')


def level_user(request):
    request.user.groups.add(Group.objects.get(name="User"))
    return HttpResponseRedirect('/')


def anon_home(request):
    return render(request, "whistleblower/home_anonymous.html")


def login(request):
    if Group.objects.count() < 3:
        create_groups()
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')

    return render(request, "whistleblower/login.html")


def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/login')


# comment

def neighbor_complaint(request):
    if request.method == "POST":
        form = NComplaintForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            # FName = form.cleaned_data["reporter_first_name"]
            # LName= form.cleaned_data["reporter_last_name"]
            # rPN = form.cleaned_data["reporter_phone_number"]
            # rE = form.cleaned_data["reporter_email"]
            # rD = form.cleaned_data["reporter_description"]
            # complaintTitle = form.cleaned_data["complaint_title"]
            # complaintType = form.cleaned_data["type_complaint"]
            # sDate = form.cleaned_data["sent_date"]
            # iDate = form.cleaned_data["incident_date"]
            # rName = form.cleaned_data["respondent_name"]
            # rLocation = form.cleaned_data["respondent_location"]
            # locationAdd = form.cleaned_data["location_address"]
            # locationDesc = form.cleaned_data["location_description"]
            # incidentDesc = form.cleaned_data["incident_description"]
            # addInfo = form.cleaned_data["additional_information"]
            # expecCompl = form.cleaned_data["expected_completion"]
            # complaint = Complaint.objects.create(reporter_first_name=FName, reporter_last_name=LName,
            #                                      reporter_phone_number=rPN, reporter_email=rE, reporter_description=rD, version=0,
            #                                      complaint_title=complaintTitle, type_complaint=complaintType, sent_date=sDate, incident_date=iDate,
            #                                      respondent_name=rName, respondent_location=rLocation, location_address=locationAdd,
            #                                      location_description=locationDesc, incident_description=incidentDesc,
            #                                      additional_information=addInfo,
            #                                      expected_completion=expecCompl, complaint_status=1)
            complaint = form.save(commit=False)
            complaint.reporter = request.user
            complaint.reporter_first_name = request.user.first_name
            complaint.reporter_last_name = request.user.last_name
            complaint.reporter_email = request.user.email
            complaint.save()
            return HttpResponseRedirect("/success")
        return render(request, "whistleblower/neighbor_complaint.html", {"form": form})
    else:
        if BuildingGroup.objects.filter(users=request.user).exists():
            form = NComplaintForm(request.user)
            return render(request, "whistleblower/neighbor_complaint.html", {"form": form})
        else:
            user = request.user
            context = {
                'name': user.username.capitalize(),
                'open_reports': Complaint.objects.filter(reporter=user,
                                                         complaint_status__in=[Complaint.ComplaintStatus.NEW,
                                                                               Complaint.ComplaintStatus.IN_PROGRESS]),
                'closed_reports': Complaint.objects.filter(reporter=user,
                                                           complaint_status=Complaint.ComplaintStatus.RESOLVED),
                'is_admin': user.groups.filter(name="Admin"),
                'is_superadmin': user.groups.filter(name="SuperAdmin"),
                'groups': BuildingGroup.objects.filter(users=request.user),
                'error_message': "Please join a group first"
            }
            return render(request, "whistleblower/home.html", context)



def building_complaint(request):
    if request.method == "POST":
        form = BComplaintForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            # FName = form.cleaned_data["reporter_first_name"]
            # LName= form.cleaned_data["reporter_last_name"]
            # rPN = form.cleaned_data["reporter_phone_number"]
            # rE = form.cleaned_data["reporter_email"]
            # rD = form.cleaned_data["reporter_description"]
            # complaintTitle = form.cleaned_data["complaint_title"]
            # complaintType = form.cleaned_data["type_complaint"]
            # sDate = form.cleaned_data["sent_date"]
            # iDate = form.cleaned_data["incident_date"]
            # rName = form.cleaned_data["respondent_name"]
            # rLocation = form.cleaned_data["respondent_location"]
            # locationAdd = form.cleaned_data["location_address"]
            # locationDesc = form.cleaned_data["location_description"]
            # incidentDesc = form.cleaned_data["incident_description"]
            # file1 = form.cleaned_data["file1"]
            # file2 = form.cleaned_data["file2"]
            # file3 = form.cleaned_data["file3"]
            # addInfo = form.cleaned_data["additional_information"]
            # expecCompl = form.cleaned_data["expected_completion"]
            # complaint = Complaint.objects.create(reporter_first_name=FName, reporter_last_name=LName,
            #                                          reporter_phone_number=rPN, reporter_email=rE, reporter_description=rD, version=0,
            #                                          complaint_title=complaintTitle, type_complaint=complaintType, sent_date=sDate, incident_date=iDate,
            #                                          respondent_name=rName, respondent_location=rLocation, location_address=locationAdd,
            #                                          location_description=locationDesc, incident_description=incidentDesc,
            #                                          file1=file1, file2=file2, file3=file3, additional_information=addInfo,
            #                                          expected_completion=expecCompl, complaint_status=1)
            complaint = form.save(commit=False)
            complaint.reporter = request.user
            complaint.reporter_first_name = request.user.first_name
            complaint.reporter_last_name = request.user.last_name
            complaint.reporter_email = request.user.email
            complaint.save()
            return HttpResponseRedirect("/success")
        return render(request, "whistleblower/building_complaint.html", {"form": form})
            # else:
            #     return HttpResponseRedirect("/failure")
    else:
        if BuildingGroup.objects.filter(users=request.user).exists():
            form = BComplaintForm(request.user)
            return render(request, "whistleblower/building_complaint.html", {"form": form})
        else:
            user = request.user

templates/whistleblower/admin_report_view.html
{% load socialaccount %}
{% providers_media_js %}
{# Load the tag library #}
{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

<html>
    <head>
        <style>
            body, html {
                margin: 0;
                padding: 0;
            }
            .navbar-custom {
                background-color: #007bff;
                padding: 0.5rem 0;
            }
            .nav-item {
                color: white;
                text-decoration: none;
                padding: 0.5rem 1rem;
                display: inline-block;
            }
            .container {
                padding: 2rem 1rem;
                margin-top: 60px; /* Adjust based on navbar height */
            }
            .header {
                text-align: center;
                margin-bottom: 2rem;
            }
            .report-detail {
                margin-bottom: 1rem;
            }
            .btn-custom {
                background-color: black;
                color: white;
                border: none;
                border-radius: 25px;
                padding: 5px 10px;
                text-decoration: none;
                display: inline-block;
                margin-top: 10px;
            }
            .btn-delete {
                background-color: red;
                color: white;
                border: none;
                border-radius: 20px;
                padding: 5px 10px; /* Smaller padding for a smaller button */
                text-decoration: none;
                display: inline-block;
            }
            .section {
                border: 1px solid #ccc;
                padding: 1rem;
                border-radius: 5px;
                margin-bottom: 1rem;
            }
        </style>
        <title>Report View</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-custom fixed-top">
            <div class="container-fluid justify-content-end">
                <a class="btn nav-item" href="{% url 'whistleblower:home' %}">Home</a>
            </div>
        </nav>
        {% block content %}

        <div class="container">
            <div class="header">
                <h1>Report View</h1>
                {% if not is_admin %}
                    <a href="{% url 'whistleblower:delete' report.id %}" class="btn-delete">Delete</a>
                {% endif %}
            </div>
            <div class="section">
                <p class="report-detail"><strong>Reporter:</strong> {{report.reporter_first_name}} {{report.reporter_last_name}}</p>
                <p class="report-detail"><strong>Reporter Email:</strong> {{report.reporter_email}}</p>
                <p class="report-detail"><strong>Complaint Title:</strong> {{report.complaint_title}}</p>
                <p class="report-detail"><strong>Complaint Type:</strong> {{report.complaint_type_phrase}}</p>
                <p class="report-detail"><strong>Sent Date:</strong> {{report.sent_date}}</p>
                <p class="report-detail"><strong>Incident Date:</strong> {{report.incident_date}}</p>
                <p class="report-detail"><strong>Respondent Name:</strong> {{report.respondent_name}}</p>
                <p class="report-detail"><strong>Location Address:</strong> {{report.location_address}}</p>
                <p class="report-detail"><strong>Location Description:</strong> {{report.location_description}}</p>
                <p class="report-detail"><strong>Incident Description:</strong> {{report.incident_description}}</p>
                <p class="report-detail"><strong>Additional Info:</strong> {{report.additional_information}}</p>
                <p class="report-detail"><strong>Urgency:</strong> {{report.urgency}}</p>
                <p class="report-detail"><strong>Status:</strong> {{report.complaint_status_phrase}}</p>
                {% if report.file1 == "" %}
                <div>
                    <p> File 1: None </p>
                </div>
                {% elif 'jpg' in report.file1 %}
                <div>
                    <img src="{{ report.file1.url }}" alt="Uploaded Image" style="width: 100%; height: auto;">
                </div>
                {% elif 'txt' in report.file1 %}
                <div>
                    <iframe src="{{ report.file1.url }}" alt="Uploaded Text File"></iframe>
                </div>
                {% else %}
                <div>
                    <embed src ="{{ report.file1.url }}" alt="Uploaded PDF" style="width: 100%; height:100%">
                </div>
                {% endif %}
                {% if report.file2 == "" %}
                <div>
                    <p> File 2: None </p>
                </div>
                {% elif 'jpg' in report.file2 %}
                <div>
                    <img src="{{ report.file2.url }}" alt="Uploaded Image" style="width: 100%; height: auto;">
                </div>
                {% elif 'txt' in report.file2 %}
                <div>
                    <iframe src="{{ report.file2.url }}" ></iframe>
                </div>
                {% else %}
                <div>
                    <embed src = "{{ report.file2.url }}" alt="Uploaded PDF" style="width: 100%; height:100%">
                </div>
                {% endif %}
                {% if report.file3 == "" %}
                <div>
                    <p> File 3: None </p>
                </div>
                {% elif 'jpg' in report.file3 %}
                <div>
                    <img src="{{ report.file3.url }}" alt="Uploaded Image" style="width: 100%; height: auto;">
                </div>
                {% elif 'txt' in report.file3 %}
                <div>
                    <iframe src="{{ report.file3.url }}" ></iframe>
                </div>
                {% else %}
                <div>
                    <embed src = "{{ report.file3.url }}" alt="Uploaded PDF" style="width: 100%; height:100%">
                </div>
                {% endif %}
            </div>

            {% if is_admin %}
            <div class="section">
                {% if resolved %}
                <form method="post" action="{% url 'whistleblower:reopen_report' report.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn-custom">Reopen Report</button>
                </form>
                {% else %}
                <form method="post" action="{% url 'whistleblower:mark_as_resolved' report.id %}">
                    {% csrf_token %}
                    <textarea id="resolution_notes" name="resolution_notes" rows="5" cols="50" class="form-control"></textarea>
                    <button type="submit" class="btn-custom">Mark as Resolved</button>
                </form>
                {% endif %}
            </div>
            {% else %}
            <div class="section">
                <h5>Admin Notes</h5>
                {% if has_notes %}
                <p>{{ report.resolution_notes }}</p>
                {% else %}
                <p>No notes available at this time.</p>
                {% endif %}
            </div>
            {% endif %}
        </div>
        <div class=footer>
            {% include 'whistleblower/footer.html' %}
        </div>
        {% endblock content %}      
    </body>
</html>

templates/whistleblower/home.html
{% load socialaccount %}
{% providers_media_js %}
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}



<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body, html {
            margin-top: 0;
            padding-top: 0;
        }
        .navbar-custom {
            background-color: #007bff;
        }
        .nav-item {
            color: white;
            background-color: #007bff;
        }
        .dashboard-header {
            text-align: center;
            margin-bottom: 2rem;
        }
        .dashboard-buttons .btn {
            margin: 0.5rem;
        }
        .dashboard-buttons .btn-dark:hover {
            background-color: #fff; 
            color: #000; 
            border: 1px solid #000;
        }
        .reports-container {
            display: flex;
            justify-content: space-around; 
            margin-top: 2rem;
        }
        .report-list, .groups-section{
            border: 2px solid #343a40; 
            padding: 1rem;
            border-radius: 0.25rem; 
            width: 48%; 
        }
        .groups-section {
            margin: 2rem auto; 
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
        }
        .groups-list {
            list-style: none; 
            padding: 0;
        }
        .groups-list li {
            padding: 10px;
        }
        .groups-list li:hover {
            background-color: #f0f0f0; 
            border-radius: 25px;
        }
        .groups-list a {
            display: none; 
        }
        .groups-list li:hover a {
            display: inline;
        }
    </style>

    <Title>Home</Title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-custom fixed-top">
            <div class="container-fluid justify-content-end">
                <a class="btn nav-item" href="{% url 'whistleblower:logout' %}">Logout</a>
            </div>
        </nav>
        <div class="dashboard-header mt-5 pt-5">
            <h1>Welcome to your dashboard, {{ name }}!</h1>
        </div>
        <div class="dashboard-buttons d-flex justify-content-center">
            <a class="btn btn-dark" href="{% url 'whistleblower:join_group_page' %}">Join a Building</a>
            <a class="btn btn-dark" href="{% url 'whistleblower:n-complaint' %}">Neighbor Report Form</a>
            <a class="btn btn-dark" href="{% url 'whistleblower:b-complaint' %}">Building Report Form</a>
        </div>
        <div class ="text-center">
            {{ error_message }}
        </div>
        <div class="reports-container">
            <div class="report-list">
                <h2>Open Reports</h2>
                <ul>
                    {% for report in open_reports %}
                        <li>
                            <a href="{% url 'whistleblower:report_view' report.id %}">
                                {{ report.complaint_title }} - {{ report.sent_date }}
                            </a>
                        </li>
                    {% empty %}
                        <p>No open reports.</p>
                    {% endfor %}
                </ul>
            </div>
            <div class="report-list">
                <h2>Closed Reports</h2>
                <ul>
                    {% for report in closed_reports %}
                        <li>
                            <a href="{% url 'whistleblower:report_view' report.id %}">
                                {{ report.complaint_title }} - {{ report.sent_date }}
                            </a>
                        </li>
                    {% empty %}
                        <p>No closed reports.</p>
                    {% endfor %}
                </ul>
            </div>
        </div>


        <div class="groups-section">
            <h3>Groups</h3>
            {% for group in groups %}
            <ul class="groups-list">
                <li>
                    {{group.name}} <a href="{% url 'whistleblower:leave_building_group' group.pk %}">Leave</a>
                </li>
            </ul>
            {% endfor %}
        </div>



    </div>
    <div class=footer>
        {% include 'whistleblower/footer.html' %}
    </div>
</body>
</html>

templates/whistleblower/home_admin.html
{% load socialaccount %}
{% providers_media_js %}
{# Load the tag library #}
{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin Home</title>
    <style>
        body, html {
                margin-top: 0;
                padding-top: 0;
            }
            .navbar-custom {
                background-color: #007bff;
            }
            .nav-item {
                color: white;
                background-color: #007bff;
            }
            .dashboard-header {
                text-align: center;
                margin-bottom: 2rem;
            }
            .dashboard-subheader {
                text-align: center;
                color: #343a40;
            }
            .dashboard-buttons .btn {
                margin: 0.5rem;
            }
            .dashboard-buttons .btn-dark:hover {
                background-color: #fff; 
                color: #000; 
                border: 1px solid #000;
            }
            .reports-container {
                display: flex;
                justify-content: space-around; 
                margin-top: 2rem;
            }
            .report-list {
                border: 2px solid #343a40; 
                padding: 1rem;
                border-radius: 0.25rem; 
                width: 48%; 
            }
        .scrollable-box{
                padding: 2rem;
                position: absolute;
                top: 120px;
                bottom: 100px;
                left: 180px;
                width: 50%;
                overflow-y: scroll;
        }
    </style>
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-custom fixed-top">
            <div class="container-fluid justify-content-end">
                <a class="btn nav-item" href="{% url 'whistleblower:create_group_page' %}">Create Building Group</a>
                <a class="btn nav-item" href="{% url 'whistleblower:logout' %}">Logout</a>
            </div>
        </nav>
        <div class="dashboard-header mt-5 pt-5">
            <h1>{{ name }}'s Admin Dashboard</h1>
        </div>
        <div class="dashboard-buttons d-flex justify-content-center">
            
        </div>
        {% if groups %}
        <div class="dashboard-subheader">
            <h5> Open Reports </h5>
        </div>
        {% for group in groups %}
        <div class="container border rounded-top">
            <p>{{ group.name }}  | Code: {{ group.pk }}</p>
        </div>
        <div class="container border rounded-bottom" style="height: 100px; overflow-y: scroll;">
            <ul>
            {% for report in reports %}
                {% if report.group == group %}
                <li><a href="{% url 'whistleblower:report_view' report.id %}">{{ report.complaint_title }}</a> | Urgency: {{ report.urgency }}</li>
                {% endif %}
            {% endfor %}
            </ul>
        </div>
        {% endfor %}
        <br>
        <div class="dashboard-subheader">
            <h5> Closed Reports </h5>
        </div>
        {% for group in groups %}
        <div class="container border rounded-top">
            <p>{{ group.name }}  | Code: {{ group.pk }}</p>
        </div>
        <div class="container border rounded-bottom" style="height: 100px; overflow-y: scroll;">
            <ul>
            {% for report in closed_reports %}
                {% if report.group == group %}
                    <li><a href="{% url 'whistleblower:report_view' report.id %}">{{ report.complaint_title }}</a></li>
                {% endif %}
            {% endfor %}
            </ul>
        </div>
        {% endfor %}
        {% else %}
            <p>No current groups. Please create a new group and get your residents to join.</p>
        {% endif %}
        <title>Admin Home</title>
    </div>
    <div class=footer>
        {% include 'whistleblower/footer.html' %}
    </div>
</body>


</html>